$image = /home/azel/Music/wallpapers/wallhaven-lyzvdl.png

$background = rgba(16111bff)

$error = rgba(ffb4abff)

$error_container = rgba(93000aff)

$inverse_on_surface = rgba(332e39ff)

$inverse_primary = rgba(8100f5ff)

$inverse_surface = rgba(e9dfeeff)

$on_background = rgba(e9dfeeff)

$on_error = rgba(690005ff)

$on_error_container = rgba(ffdad6ff)

$on_primary = rgba(440087ff)

$on_primary_container = rgba(eddcffff)

$on_primary_fixed = rgba(290055ff)

$on_primary_fixed_variant = rgba(6200bdff)

$on_secondary = rgba(3d2946ff)

$on_secondary_container = rgba(f6d9ffff)

$on_secondary_fixed = rgba(271430ff)

$on_secondary_fixed_variant = rgba(543f5eff)

$on_surface = rgba(e9dfeeff)

$on_surface_variant = rgba(ccc3d2ff)

$on_tertiary = rgba(472248ff)

$on_tertiary_container = rgba(ffd6f9ff)

$on_tertiary_fixed = rgba(300d31ff)

$on_tertiary_fixed_variant = rgba(603960ff)

$outline = rgba(968e9bff)

$outline_variant = rgba(4a4450ff)

$primary = rgba(d7baffff)

$primary_container = rgba(6200bdff)

$primary_fixed = rgba(eddcffff)

$primary_fixed_dim = rgba(d7baffff)

$scrim = rgba(000000ff)

$secondary = rgba(d9bde3ff)

$secondary_container = rgba(543f5eff)

$secondary_fixed = rgba(f6d9ffff)

$secondary_fixed_dim = rgba(d9bde3ff)

$shadow = rgba(000000ff)

$source_color = rgba(7d47c6ff)

$surface = rgba(16111bff)

$surface_bright = rgba(3c3742ff)

$surface_container = rgba(221e28ff)

$surface_container_high = rgba(2d2833ff)

$surface_container_highest = rgba(38333eff)

$surface_container_low = rgba(1e1a24ff)

$surface_container_lowest = rgba(100c16ff)

$surface_dim = rgba(16111bff)

$surface_tint = rgba(d7baffff)

$surface_variant = rgba(4a4450ff)

$tertiary = rgba(eab6e5ff)

$tertiary_container = rgba(603960ff)

$tertiary_fixed = rgba(ffd6f9ff)

$tertiary_fixed_dim = rgba(eab6e5ff)

